Add files via upload
No matter what I did, I continue to get this error line
Exercise3_3.java:26: error: 'else' without 'if'
		else { 
		^
I had Stacy help me, and she says it should work as it is. So we are stuck on this.